(setq-default theming-modifications
              '((doom-molokai
                 (default :background "#282828")
                 (linum-highlight-face :background "#292929" :foreground "#FD971F")
                 (org-level-1 :background "#282828")
                 (helm-source-header :foreground "#F92672" :background "#282828")
                 (mode-line :box (:color "#353535" :line-width 1)
                            :background "#353535")
                 (powerline-active0 :box (:color "#353535" :line-width 1)
                                    :background "#353535")
                 (powerline-active1 :box (:color "#353535" :line-width 1)
                                    :background "#353535")
                 (powerline-active2 :box (:color "#494848" :line-width 1)
                                    :background "#494848")
                 (mode-line-inactive :box (:color "#353535" :line-width 1)
                                     :background "#202020")
                 (powerline-inactive1 :box (:color "#353535" :line-width 1)
                                      :background "#272727")
                 (powerline-inactive2 :box (:color "#353535" :line-width 1)
                                      :background "#353535")
                 (mode-line-buffer-id :foreground "#A6E22E")
                 (helm-prefarg :foreground "PaleGreen")
                 (sp-show-pair-match-face :background "#4E4E4E")
                 (match :background "#4E4E4E")
                 )))

